### ISSUE TITLE
How comparable are the scores returned by best_match?

### ISSUE THREAD

**Issue by Boscop** [Schlechtwetterfront/fuzzy-rs#1]
1. I want to find the most likely file that is meant by a user entering the file name.
Can I just compare the scores returned by `best_match` (and use the highest one) or are they not comparable across different target strings (same pattern string)?

2. If I want case insensitive matching, do I have to lowercase both the pattern and target strings? Or only the pattern string?

**Comment by Schlechtwetterfront** [comment]
1. The better the target matches the pattern the higher the score. So, yes.
2. Both should be lowercased. The only processing that is applied to the _pattern_ is the removal of white space.

Do you think the documentation should be amended in some way to make things clearer?

Feel free to open tickets if you encounter any issues or weird results.

**Comment by Boscop** [comment]
Thanks for the quick reply :)
Yes, it would be helpful to have those two sentences in the docs.

Btw, is this the exact same algorithm as used in sublime's jump menu (Ctrl+P) and command palette (Ctrl+Shift+P)?
Or just inspired by it?

**Comment by Boscop** [comment]
Also it would be useful to know (and put in the docs) under what conditions `best_match()` returns `None`, and what the lowest returned score could be :)

**Comment by Schlechtwetterfront** [comment]
It's inspired, but doesn't have as many 'features' (yet?). Sublime's algorithm does more, like higher scoring of word boundaries (**W**ord**B**oundary) and recognizing small typos like exchanging two adjacent letters.

Thanks for the suggestions, I'll make sure to include those in the next update.

**Comment by Boscop** [comment]
Thanks.

Btw, it's working well. Is it correct to use `-1`, or what's the lowest possible score that it returns?
I'm using it like this:
```rust
	fn find_param(&self, find_param: &FxParamId<&'static str>) -> Option<FxParamId<usize>> {
		let find_param = find_param.to_lowercase();
		fn best_match2(needle: &str, haystack: &str) -> isize {
			best_match(needle, haystack).map_or(-1, |m| m.score())
		}
		self.tracks.iter().enumerate().max_by_key(|&(_, track)|
			best_match2(&find_param.track, &track.name.to_lowercase())
		).and_then(|(track_i, track)|
			track.plugins.iter().enumerate().max_by_key(|&(_, plugin)|
				best_match2(&find_param.plugin, &plugin.name.to_lowercase())
			).and_then(|(plugin_i, plugin)|
				plugin.params.iter().enumerate().max_by_key(|&(_, param)|
					best_match2(&find_param.param, &param.to_lowercase())
				).map(|(param_i, _param)|
					FxParamId { track: track_i, plugin: plugin_i, param: param_i }
				)
			)
		)
	}
```
This is the correct way to use it case-insensitively, right?

(Btw, the actual version I'm using now is using [mdo](https://github.com/TeXitoi/rust-mdo) to prevent the increasing indentation:
```rust
	fn find_param(&self, find_param: &FxParamId<&'static str>) -> Option<FxParamId<usize>> {
		let find_param = find_param.to_lowercase();
		fn best_match2(needle: &str, haystack: &str) -> isize {
			best_match(needle, haystack).map_or(-1, |m| m.score())
		}
		mdo! {
			(track_i, track) =<< self.tracks.iter().enumerate().max_by_key(|&(_, track)|
				best_match2(&find_param.track, &track.name.to_lowercase())
			);
			(plugin_i, plugin) =<< track.plugins.iter().enumerate().max_by_key(|&(_, plugin)|
				best_match2(&find_param.plugin, &plugin.name.to_lowercase())
			);
			(param_i, _param) =<< plugin.params.iter().enumerate().max_by_key(|&(_, param)|
				best_match2(&find_param.param, &param.to_lowercase())
			);
			ret ret(FxParamId { track: track_i, plugin: plugin_i, param: param_i })
		}
	}
```
)

**Comment by Schlechtwetterfront** [comment]
It can go lower than `-1` as the current algorithm will subtract points for distance between characters. So if you had a very long target string (`abc ... xyz`) and your pattern was something like `az` then it would subtract for all the characters inbetween. Which doesn't really make a lot of sense because if no characters at all match then it will return a match with a score of 0.

I guess it would make more sense to have no-matches return `None` and try to clamp the actual matches to some range?

**Comment by Boscop** [comment]
Yes, a very unlikely match should score higher than a non-match.
So non-matches should either return `std::isize::MIN` as score, but `None` is even better because it makes more semantic sense, and then one could easily check if there was ANY match at all by filtering out the `None`s.

Right now, `best_match` only returns `None` `if condensed.len() == 0 || target.len() == 0`?
So I'd prefer if it also returns `None` when there is no match.

Btw, I changed my function to filter out the `None` matches instead of using `-1` for them, so it will work as intended if `best_match` is changed to return `None` for non-matches.

Then it wouldn't be necessary to clamp the scores. And not clamping them would retain the true resolution of the score space, so that e.g. `"ay"` would still score higher in `"abc ... xyz"` than in `"abc ... xzy"`.

**Comment by Schlechtwetterfront** [comment]
Alright, as part of a bigger rewrite it should now return `None` if a match does not succeed. Value range is still full `isize` range.
