### ISSUE TITLE
Matching score could be improved to account for target coverage / specificity

### ISSUE THREAD

**Issue by Boscop** [Schlechtwetterfront/fuzzy-rs#2]
When the pattern is "release" and tested against the targets "release" and "a.release", it will give both the same score (448), but it would be better to give a higher score for a pattern that covers more chars of the target.
In this case, all of the pattern's chars are found in "release", so the coverage is 1.0, but the coverage of "a.release" is only 7/9=0.777.
Now this coverage ratio can be multiplied with some other factor in the score formula (maybe not necessarily multiplied with the final score), to **ensure that fuller (and thus more specific) matches get higher scores**.
Not sure if this idea is too simple but I think it should work.

The use case where this came up is:
I'm using [this code](http://dpaste.com/0J4BK1A) to match against FX parameters:
```rust
(param_i, _param, _) =<< plugin.params.iter().enumerate().filter_map(|(i, param)|
	best_match2(&find_param.param, &param.to_lowercase()).map(|score| (i, param, score))
).max_by_key(|&(_, _, score)| score);
```
And there is an FX plugin that has these two parameter names, so when I meant to find the param named "release", it found "a.release" instead because both got the same score :(
(And for `max_by_key`: `If several elements are equally maximum, the last element is returned.` )

---

Maybe there are better ways to give them different scores so that it would find the intended one, but the above coverage ratio was the first idea that came to mind..

As long as this issue exists, there is no way for me to write the pattern differently in my config file so that it will find the intended param, because it already is as specific as it can be.

**Comment by Boscop** [comment]
As a temporary workaround, I'm using `.sorted_by_key(|&(_, param, _)| Reverse(param.len())).into_iter()` before `.max_by_key` now, but that causes extra memory allocations..

**Comment by Schlechtwetterfront** [comment]
Seems like a good idea. I just wonder how exactly to incorporate that into the score. Multiple the final score or have some bonus that is multiplied by the coverage.

So if both have a score of `448` `'release'` would get `1.0 * 50 = 50` and `'a.release'` would get `.7 * 50 = 35` bonus score.

Edit: That way users could also adjust how much they want to weight coverage.

**Comment by Boscop** [comment]
But as a user, I think it's enough to specify via a bool arg if coverage should be accounted for or not, and if yes, it will use an appropriate `max_bonus` to multiply with.
Btw, in which use cases **wouldn't** you want to incorporate coverage into the score?
Maybe it could just be the default / only option?

**Comment by Schlechtwetterfront** [comment]
Hmm, what if you're searching file paths for file names? A file that's closer to the root will get a higher score even if the filename itself might not match as well.

But it definitely makes sense to have it as the default.

**Comment by Boscop** [comment]
What do you mean by "A file that's closer to the root will get a higher score even if the filename itself might not match as well."? What root? 

If by "root" you mean the beginning of a path, and you want to give preference to matching the filename at the end of the path, you could just combine the scores of matching the search string against the whole path, and matching only against the filename.

EDIT: Ah, I guess you mean, if there are two paths like "/foo/bar/baz.md" and "/bar.md" then searching for "baz" might give the 2nd one a higher score?
I think the solution to that is to have a couple of test cases and tweak the bonus factor..

But yea, it could be an extra config arg to enable coverage scoring.
And it could also be an extra config arg to give more weight to matches at the beginning or end of the target string, so that matches of filenames (at the end of the path) get weighted higher, whereas other use cases might give more weight to matches at the beginning (e.g. text editor open buffer switcher that only matches against filenames (which could be very long)).

In any case, I think it makes sense to have a couple of test cases with desired score ranking orders and then do some (automatic) testing to determine the factors that satisfies all the test case rankings.

**Comment by Schlechtwetterfront** [comment]
Yes, if you had `some/longer/path.h` and `/pattern.h` and were looking for `path` it would score `/pattern.h` higher because it has a higher coverage.

Defining some test cases is a great idea. Have any suggestions?

`a.release` < `release` or something of that type could be one.

**Comment by Schlechtwetterfront** [comment]
I've implemented the coverage as a flat bonus (default currently: 64) that gets multiplied by the coverage and will be added on top of the final score.

I'm planning on adding a few more tests to make sure the results are mostly as expected so it's not up on crates.io yet.
