### ISSUE TITLE
Eliminating unwanted matches

### ISSUE THREAD

**Issue by Boscop** [Schlechtwetterfront/fuzzy-rs#3]
How does the score relate to the number of chars matched?

I'm asking because I want to eliminating unwanted matches.
E.g. let's say the `needle` is `"reverb"` and the `haystack` is `"roller"`, then I wouldn't want to accept this as a match, even though they have 3 chars in common. (Or even when `haystack` is `"render"` with 4 chars in common.)

Should I just increase the `bonus_consecutive`? Is that for consecutive chars or words? And is `penalty_distance` the penalty for distance between consecutive streaks of chars?

What is the difference between using a higher `bonus_consecutive` and a lower `penalty_distance`?

And which threshold should I use to eliminate the bad matches if they get a low score (because as soon as they have 1 char in common, they will get Some(score), right)?

Which values for both bonuses should I use so that only if a word in `needle` also occurs as a consecutive group in `haystack` will it constitute a match? Would it be possible to **NOT** eliminate the whitespace in `needle` so that matched groups can get higher scores (proportional to group length))?

**Comment by Schlechtwetterfront** [comment]
It will only ever return a `Some(...)` if the pattern is _fully_ matched.

The distance penalty is just `distance * penalty`.

The bonus works like this (there might be a mathematical term for this but I don't know it).
```
                 0
p -> + 0 * 5 =   0
a -> + 1 * 5 =   5
t -> + 2 * 5 =  15
t -> + 3 * 5 =  30
e -> + 4 * 5 =  50
r -> + 5 * 5 =  75
n -> + 6 * 5 = 105
```

> Which values for both bonuses should I use so that only if a word in `needle` also occurs as a consecutive group in `haystack` will it constitute a match?

As long as `needle` appears in `haystack` there will be a match. You can obviously increase the consecutive match bonus a lot to weigh that more.

The whitespace is removed to prevent the algorithm from branching at every whitespace in the target string. Leaving it in wouldn't have the intended effect. That would have to be implemented.

But for your use case wouldn't something different be a better choice? If you only want consecutive matches, can't you do a direct `target.contains(word)` for every word? That would be a lot more efficient.
