### ISSUE TITLE
Does not match when search is reversed

### ISSUE THREAD

**Issue by isamert** [Schlechtwetterfront/fuzzy-rs#8]
Not quite sure how to put it on title but the example will be quite clear I hope:

This works, I get a match:
```
    let s = "some search thing";
    let search = "some search";
    let result = best_match(search, s);
    assert!(result.is_some());
```

But this does not match, returns `None`:
```
    let s = "some search thing";
    let search = "search some";
    let result = best_match(search, s);
    assert!(!result.is_some());
```

Is this intended behavior?

**Comment by isamert** [comment]
Now that I think of this, it makes sense that it does not match. What would be the best way to achieve this? A naive approach would be splitting the query with  space, running algorithm for each word and summing the scores. I guess fuzzy finders like fzf does something similar.

**Comment by Schlechtwetterfront** [comment]
Yeah, this is sort of implicitly intended. Switching around the order would be problematic with the current scoring (although I haven't really thought too much about it).

Your approach could work, but I see some issues where:

* Some of the query words match in the same (overlapping) part of the searched string. 
* You lose some of the scoring like distance penalties.

I'm not sure if there's currently a better approach though.
